twig:
    default_path: '%kernel.project_dir%/templates'
    cache:  false
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    auto_reload:               true
    optimizations:             -1

when@test:
    twig:
        strict_variables: true
